// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjgdlahmrbrmjxeixbcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqZ2RsYWhtcmJybWp4ZWl4YmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMTU3NjMsImV4cCI6MjA4NDU5MTc2M30.b3FCJS66vPp2Fs_OqcV35wCyaGMj_nchDHM9xU_hQn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});